import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toast } from "@heroui/react";
import "@fortawesome/fontawesome-free/css/all.min.css";
import Sidebar from "./(components)/SideBar/SideBar";
import UserContextProvider from "./Context/UserContext";
import { getMyProfile } from "./services/user.service";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children}: Readonly<{children: React.ReactNode}>){
  
  const user = await getMyProfile();
  return (
    <>
    <html lang="en" className={`h-full antialiased `}>
      <body className="flex flex-col min-h-screen">
     <UserContextProvider loggedUser = {user}>
       <Sidebar />
        {children}
     </UserContextProvider>
      <Toast.Provider placement="top"/>
        </body>
    </html>
      </>
  )
}
